import { Inter } from "@next/font/google";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { useGetAllProductQuery } from "../api/UserApi";
import Card from "../src/components/Card";
import Hero from "../src/components/Hero";
import Loader from "../src/components/Loader";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [show, setShow] = useState(false);
  const { data, isLoading, error } = useGetAllProductQuery({});

  return (
    <>
      <Head>
        <title>Aide Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-100 pb-16  overflow-hidden">
        <Hero />
        {/* products */}

        <div className="my-5 py-5">
          <div className="container mx-auto">
            <div className="flex justify-center items-center flex-col   mx-auto sm:w-[60rem] mb-16">
              <h1 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl xl:text-5xl text-center text-gray-800 font-black leading-7 md:leading-5">
                Our Products
              </h1>
              <p className="mt-0 sm:mt-1 lg:w-10/12 text-gray-400 font-normal text-center text-sm sm:text-lg">
                A professonal website drives sales. Create a beautiful website
                to impress and engage new customers and establish your business
                online
              </p>
            </div>
            {isLoading ? (
              <Loader />
            ) : (
              <>
                {data?.products?.length > 0 ? (
                  <>
                    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2">
                      {data?.products?.slice(0, 4)?.map((item: any) => (
                        <Card key={item?._id} item={item} />
                      ))}
                    </div>
                  </>
                ) : (
                  <h2 className="text-xl text-center py-5">No data found</h2>
                )}
              </>
            )}

            <div className="text-right">
              <Link href={"/products"} className="underline mt-5 inline-block">
                Get All Products
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
